In [5]:
def exceptFunc(a,b):
    try:
        print(a/b)
    except ZeroDivisionError:
        print('Error: ZeroDivisionError')
 
a= int(input('Enter 1st number'))
b= int(input('Enter 2nd number'))
exceptFunc(a,b)

Enter 1st number5
Enter 2nd number0
Error: ZeroDivisionError


In [4]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print(s,v,o)
            

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [40]:
import numpy as np

def func(l,b):
    new_l =[]
    l2 =[]
    n=len(l)
    if b==True:
        for i in l:
            for j in range(n):
                l2.append(pow(i,j))
            new_l.append(l2)
            l2=[]
        
        arr = np.array(new_l)
        print(arr)
    
    elif b==False:
        for i in l:
            for j in range(n):
                l2.append(pow(i,n-j-1))
            new_l.append(l2)
            l2=[]
       
        arr = np.array(new_l)
        print(arr)
    else:
        print('Invalid Input !')
    
l = eval(input('Enter a list:'))
b= bool(input('Enter True or False:'))
func(l,b)

Enter a list:[2,3,4]
Enter True or False:True
[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
